# Generated by Django 5.1.4 on 2024-12-14 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_nss_participant_nss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='full',
        ),
    ]
