# Generated by Django 5.1.4 on 2024-12-15 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_team_full'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
