# Generated by Django 5.1.4 on 2024-12-15 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_challenge_submission_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='challenges/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hackaton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Challenges', to='api.hackaton')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('githubLink', models.URLField()),
                ('driveLink', models.URLField()),
                ('figmaLink', models.URLField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.challenge')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.team')),
            ],
        ),
    ]
